### ISSUE TITLE
self.token.column chyba nie działa

### ISSUE THREAD

**Issue by GrzesiuKo** [knigawkl/compiler#1]
https://github.com/knigawkl/compiler/blob/2b4dcfcf4b9e9c20a82053bbd8a857682b358ebd/compose-validator/parser.py#L140

Sprawdzałeś printem czy column Ci się zgadza, bo u mnie ta wartość z każdym wywołaiem rośnie.

Chodzi o ostatni "if"

**Comment by knigawkl** [comment]
U mnie działa.

**Comment by GrzesiuKo** [comment]
ok
